apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-parent-dbiu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-parent-dbiu
    app.kubernetes.io/part-of: build-suite-component-update-yeqm
  name: multi-component-parent-dbiu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-parent-dbiu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-parent-dbiu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-mthr-tenant/build-suite-component-update-yeqm/multi-component-parent-dbiu@sha256:85eb36a6e5e0a321085b968f45a2fe130dd54af3635215c6205506f2bc0f2cae
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
