apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-component-parent-dbiu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-mthr-tenant/build-suite-component-update-yeqm/multi-component-parent-dbiu@sha256:85eb36a6e5e0a321085b968f45a2fe130dd54af3635215c6205506f2bc0f2cae
        name: container-image
        resources: {}
status: {}
